### ISSUE TITLE
When using a video filename with spaces, getting: "VTT File Not Found!"

### ISSUE THREAD

**Issue by eyalroz** [innovatorved/subtitle#6]
I've cloned the master branch and am running `subtitle.py` on an MP4 file, using the base model. I get:
```
Model base exists
file /path/to/file.mp4 data/7b8ad9cb-f715-4926-8fe1-53e81ad50cf8.wav.vtt /path/to/file_subtitled.mp4
An error occurred: An error occurred: VTT File Not Found!
ERROR:root:An error occurred: cannot unpack non-iterable NoneType object
```
I don't know what a VTT file is, and my MP4 certainly doesn't need it. Looking at the code, it seems that
```
generate_vtt_file(file, model_names[model])
```
returns a path, but - doesn't actually generate the VTT.

**Comment by innovatorved** [comment]
Share me the video file

**Comment by eyalroz** [comment]
@innovatorved : Unfortunately, I cannot. If you'd like, you can send me some executable you'd like to run on the video file... I'm using Devuan GNU/Linux.

**Comment by SchroederIV** [comment]
For me it was that the filename had spaces in its name.

@innovatorved The output of this tool is very impressive.
It really catches subleties and slang (Always Sunny in Philadelphia).
Do you think it is possible to add translation to your tool?
I have no clue about AI but I know python.

**Comment by innovatorved** [comment]
> For me it was that the filename had spaces in its name.
> 
> @innovatorved The output of this tool is very impressive. It really catches subleties and slang (Always Sunny in Philadelphia). Do you think it is possible to add translation to your tool? I have no clue about AI but I know python.

It already translate non english speech to english subtitles

**Comment by eyalroz** [comment]
> For me it was that the filename had spaces in its name.

My actual filename also had spaces. Will try avoiding those.

It's too bad that the error messages are not verbose enough, we could have been told what filename the program was looking for...

**Comment by SchroederIV** [comment]
@innovatorved

I've seen your example video. Just fascinating.

I meant to add an additional step to the "pipeline" to translate the recognized text from whisper (which will always be english, right?) to a different language other than english before merging in with the video file.

I already looked into the commandline options of whisper. There are -dl, -l and -tr but I don't think they're meant for a subsequent translation to a different language than english.

So I guess there has to be added an additional step to perform the translation and I'll definitely look into it when I got time. I just started to add subtitles manually for said series in another language manually and it's so timeconsuming I won't be able to do it. Your tool will eliviate that pain.

Thanks for your work to piece together all the moving parts.

**Comment by SchroederIV** [comment]
I tried the offline Argos and Marian machine translation with pytorch following [this guides](https://skeptric.com/python-offline-translation/index.html) and got pretty humbled.

With the Helsinki-NLP/opus-mt model for Marian and the advides argosmodel the translations where in parts very good, with maybe a fourth to third of the translations was grammatically wrong without anywhere nere the sophistication of deepl (of course).

As I read on the the Marian site you're able to train new models by providing simple line by line textfiles with the source and target languages. So for offline translation one would probably let recognized text go through the deepl- or openai-APIs first and put that in the textfiles to train the model. 

In my case (Always Sunny) there's much slang-subteleties which deepl catched pretty good. I think the only way do do it automatically within your project would be to utilize the openai or deepl API.

**Comment by eyalroz** [comment]
@SchroederIV : I don't believe your comment is related to this bug. Please consider removing it and sending email feedback to the author.
