### ISSUE TITLE
No requirements.txt file

### ISSUE THREAD

**Issue by al3xandru** [innovatorved/subtitle#7]
I couldn't find the `requirements.txt` file as mentioned in the article https://vedgupta.in/blog/subtitle-breaking-down-language-barriers-with-ai-powered-caption-generation.

After a couple of attempts to running subtitle.py, I ended up with the following:

```
beautifulsoup4==4.12.2
certifi==2023.11.17
charset-normalizer==3.3.2
ffmpeg==1.4
filelock==3.13.1
gdown==4.7.1
idna==3.6
PySocks==1.7.1
requests==2.31.0
six==1.16.0
soupsieve==2.5
tqdm==4.66.1
urllib3==2.1.0
```

I remember actually needing only:

```
requests==2.31.0
tqdm==4.66.1
ffmpeg==1.4
```

**Comment by innovatorved** [comment]
The `requirements.txt` file was previously ignored by **Git**, but it has now removed from `.gitignore` file.
This issue has been fixed in commit https://github.com/innovatorved/subtitle/commit/262380a31e2481ad2299ac9c51dc776e711e69ff . requirements.txt is now visible.
