### ISSUE TITLE
An error occurred: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by eyalroz** [innovatorved/subtitle#8]
I'm using subtitle on an mp4 file. Here's what I get:
```
python subtitle.py /path/to/file.mp4
Model base exists
file /path/to/file.mp4 data/42537cf8-b515-42ec-bfaa-779a2fe644f2.wav.vtt /path/to/file_subtitled.23
An error occurred: An error occurred: module 'ffmpeg' has no attribute 'input'
ERROR:root:An error occurred: cannot unpack non-iterable NoneType object
```
It seems `subtitle` didn't just want ffmpeg, but something else, or more specific. Yet - the README doesn't say so, and the subtitle.py doesn't fail immediately. It calls whisper, and only once that's done remembers that it needs things I don't have. And I don't even know how to provide it with the "input" attribute.

**Comment by innovatorved** [comment]
The code currently only works on Linux. If you are running it on Linux, try reinstalling the Python package or running it in a different environment. You can try:
```bash
pip install -r requirements.txt
```

**Comment by eyalroz** [comment]
> The code currently only works on Linux.

I am running on Devuan GNU/Linux Excalibur. Python version is 3.11.6. Anyway, I reinstalled ffmpeg, and used the command you suggested - that didn't help.

Really, this script needs to be more robust.

**Comment by innovatorved** [comment]
Use GitHub Codespaces. If the error persists, please let me know.

**Comment by eyalroz** [comment]
> Use GitHub Codespaces. 

I don't quite understand what you mean.

**Comment by eyalroz** [comment]
Ok, this worked for me:

Apparently, I had several modules installed:

* ffpmeg
* ffmpeg_input
* ffmpeg-python

I removed all of them, and installed only ffpmeg-python. Then this error went away. @innovatorved : I really wish you'd do a bit more robust package-checking, to let the users know what they should or shouldn't have.
